name: Generate Contribution Graph

on:
  schedule:
    - cron: "0 9 * * *"  # Runs at 9am UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate GitHub Activity Graph
        run: |
          curl -o dist/github-contribution-graph.svg "https://activity-graph.herokuapp.com/graph?username=mhutshow&theme=react-dark"
      
      - name: Commit and push graph
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-graph.svg
          git commit -m "Generated GitHub contribution graph"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload the graph as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: contribution-graph
          path: dist/github-contribution-graph.svg
