name: Generate Snake

on:
  schedule:
    - cron: "0 9 * * *"  # Runs at 9am UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: mhutshow
          outputs: dist/snake.svg

      - name: Create output directory
        run: mkdir -p dist

      - name: Move snake.svg to the output directory
        run: mv snake.svg dist/snake.svg

      - name: Commit and push snake.svg
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Generated snake.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload the snake SVG as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
