name: Generate Snake

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: platane/gh-contribution-snake@v2
        with:
          config: https://raw.githubusercontent.com/Platane/snk/main/.github/snake-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
