name: Generate snake game

on:
  schedule:
      # Runs at 9am UTC every day
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mhutshow
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git add dist/github-contribution-grid-snake.svg
      - run: git commit -m "Generate snake gif"
      - run: git push
